services:
  server.api:
    image: ${DOCKER_REGISTRY-}serverapi
    build:
      context: .
      dockerfile: Server/Dockerfile

  client.web.server:
    image: ${DOCKER_REGISTRY-}clientwebserver
    build:
      context: .
      dockerfile: Client/ChatApp.Web/Dockerfile

